# Generated by Django 2.2.12 on 2020-05-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('PC', 'pc'), ('M', 'mobile'), ('N', 'notebook'), ('ACC', 'accessories')], default='mobile', max_length=20)),
                ('img', models.ImageField(default=False, upload_to='product_image')),
            ],
        ),
    ]
