# Generated by Django 2.2.12 on 2020-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('N', 'notebook'), ('M', 'mobile'), ('ACC', 'accessories'), ('PC', 'pc')], default='mobile', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='noimage.jpg', upload_to='product_image'),
        ),
    ]
